#!/usr/bin/env node
'use strict';
// Compile the 26 SKILL.md sources into what other harnesses can read: one .mdc rule per skill
// for Cursor, and one AGENTS.md index for everything that speaks that standard (Codex, opencode,
// Gemini CLI, Copilot, Zed, …). The skill prose is the product; only the packaging is Claude's,
// so this is a mechanical transform with a short substitution table — never a rewrite.
//
// Outputs are CHECKED IN under adapters/out/ and CI rebuilds them and diffs (the draw.io drift
// pattern): an edited SKILL.md whose compiled twin was forgotten fails the build instead of
// shipping stale.
//
// Deterministic on purpose: no timestamps, stable ordering — the drift check depends on it.

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const OUT = path.join(__dirname, 'out');
const CURSOR = path.join(OUT, 'cursor');

// What does not translate, and the mechanical fix for each. Order matters: specific first.
const SUBS = [
  // Claude's structured-question tool -> the plain act it stands for
  [/Use AskUserQuestion\b/g, 'Ask the user directly (as structured options, if your harness has a mechanism for that)'],
  [/\bAskUserQuestion\b/g, 'a direct question to the user'],
  // Claude resolves this variable at load time; nothing else will
  [/\$\{CLAUDE_PLUGIN_ROOT\}/g, '$AICOACH_REPO/plugins/__PLUGIN__'],
  // the plugin-inventory command is Claude's; elsewhere the honest equivalent is asking
  [/\brun(?:ning)? `claude plugin list`/g, 'ask the user which AI Coach rule sets they installed'],
  [/`claude plugin list`/g, 'the harness\'s plugin inventory (on Claude Code: `claude plugin list`; elsewhere, ask the user)'],
  // relative reference loads only resolve inside Claude's skill dir
  [/(\(|`|\s)references\//g, '$1$AICOACH_REPO/plugins/__PLUGIN__/skills/__SKILL__/references/'],
];

function frontmatter(text) {
  const t = text.replace(/\r\n/g, '\n');
  if (!t.startsWith('---\n')) return { fm: '', body: t };
  const end = t.indexOf('\n---', 4);
  return { fm: t.slice(4, end), body: t.slice(t.indexOf('\n', end + 1) + 1) };
}
const field = (fm, key) => (fm.match(new RegExp('^' + key + ':\\s*(.+)$', 'm')) || [])[1] || '';

const skills = [];
for (const plugin of fs.readdirSync(path.join(root, 'plugins')).sort()) {
  const dir = path.join(root, 'plugins', plugin, 'skills');
  if (!fs.existsSync(dir)) continue;
  for (const skill of fs.readdirSync(dir).sort()) {
    const file = path.join(dir, skill, 'SKILL.md');
    if (!fs.existsSync(file)) continue;
    const { fm, body } = frontmatter(fs.readFileSync(file, 'utf8'));
    skills.push({
      plugin, skill,
      description: field(fm, 'description'),
      hint: field(fm, 'argument-hint').replace(/^"|"$/g, ''),
      userOnly: /^disable-model-invocation:\s*true$/m.test(fm),
      body: SUBS.reduce((b, [re, to]) => b.replace(re, to), body)
        .replace(/__PLUGIN__/g, plugin).replace(/__SKILL__/g, skill),
    });
  }
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(CURSOR, { recursive: true });

const HEADER = (style) => `${style} Generated by adapters/build.js from plugins/*/skills/*/SKILL.md — edit the source, then
${style} \`node adapters/build.js\`. CI diffs this output against the sources, so hand edits here fail the build.
${style} Setup (once): clone https://github.com/MohammedMoataz/ai-coach, set AICOACH_REPO to the clone,
${style} and run \`node "$AICOACH_REPO/plugins/ai-coach-core/hooks/engine.js" bootstrap\` — that plants the
${style} engine every rule below shells to. Needs Node 22.16+ or 24+ (node:sqlite with FTS5).
`;

// ---- Cursor: one agent-requested .mdc per skill, flat-named for a one-glob install ----
for (const s of skills) {
  const userOnly = s.userOnly
    ? '> **User-fired by convention.** In the Claude Code original this cannot be invoked by the\n'
      + '> model at all. Cursor has no such switch, so honour it by hand: apply this rule when the\n'
      + '> user asks for this work, never proactively.\n\n'
    : '';
  const mdc = '---\n'
    + `description: "${(s.plugin + ': ' + s.description).replace(/"/g, '\\"')}"\n`
    + 'alwaysApply: false\n'
    + '---\n\n'
    + HEADER('>') + '\n'
    + userOnly + s.body;
  fs.writeFileSync(path.join(CURSOR, `${s.plugin}--${s.skill}.mdc`), mdc);
}

// ---- AGENTS.md: an index, not an inline dump — 2,200 lines of prose stays in the sources ----
let agents = '# AI Coach — for agents\n\n' + HEADER('<!--').replace(/^<!--/gm, '<!--').replace(/\n$/, ' -->\n') + `
A coaching harness: persistent team memory, debriefs that travel by git commit, deterministic
prompt checks, and documented workflows. Two ways in from any harness:

1. **MCP (the full memory, live):** register \`node "$AICOACH_REPO/adapters/mcp/server.js"\` as a
   stdio MCP server. Tools: memory_search, memory_add, memory_brief, debriefs_list, debrief_show,
   prompt_check, whoami. Publishing verbs are deliberately absent — a person fires those.
2. **The engine CLI directly:** \`ENGINE\` below always means
   \`node "$HOME/.ai-coach/bin/engine.js"\` (planted by the bootstrap above).

Names shaped like \`/plugin-name:skill\` refer to sibling workflows in this same set. Workflows
marked *user-fired* are run when the user asks, never proactively — in the Claude Code original
that is machine-enforced; here it is a convention you are trusted to keep.

## Start of a session

Run \`ENGINE brief\` (or the \`memory_brief\` MCP tool) and read it before doing anything else —
it is the ranked memory of this project: constraints, traps, and what teammates already learned.
Claude Code injects this automatically; in this harness it is your first move.

## The workflows
`;
for (const plugin of [...new Set(skills.map((s) => s.plugin))]) {
  agents += `\n### ${plugin}\n\n`;
  for (const s of skills.filter((x) => x.plugin === plugin)) {
    agents += `- **${s.skill}**${s.userOnly ? ' *(user-fired)*' : ''}`
      + (s.hint ? ` — \`${s.hint}\`` : '') + `\n  ${s.description}\n`
      + `  Full instructions: \`$AICOACH_REPO/plugins/${plugin}/skills/${s.skill}/SKILL.md\`\n`;
  }
}
agents += `
## Rules that always hold

- Every claim in produced research or docs names a source or is marked \`UNVERIFIED\`.
- One fact per memory; publishing a debrief or exporting a seed is always the user's own act.
- Nothing model-written may pass for something a person decided: memory provenance
  (\`human\`/\`distilled\`/\`imported\`) is never promoted.
`;
fs.writeFileSync(path.join(OUT, 'AGENTS.md'), agents);

console.log(`compiled ${skills.length} skills -> ${path.relative(root, CURSOR)} (${skills.length} rules) + adapters/out/AGENTS.md (${agents.split('\n').length} lines)`);
